name: Bug Report (バグレポート)
description: Create a bug report
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: バグレポート、ありがとうございます！\n可能な限り、フォームへの入力をお願いします。簡潔かつ明確に。
  - type: input
    id: os
    attributes:
      label: OS
      value: macOS
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: ブラウザ
      description: 'ブラウザは何をお使いですか？'
      placeholder: Chrome 96
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: 内容
      description: バグの内容を記載してください。
      placeholder: ダッシュボードからボタンがクリックできず、画面遷移ができない。
    validations:
      required: true
  - type: textarea
    id: reenactment
    attributes:
      label: 再現手順
      description: バグを再現するために手順を記載してください。
      placeholder: シークレットモードでログイン後、ダッシュボードでリロードをすると動作しない。
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: 挙動
      description: 本来の正常な挙動、意図している挙動を記載してください。
      placeholder: ダッシュボードから全てのページへの画面遷移が可能であること。
  - type: textarea
    id: solution
    attributes:
      label: 解決案
      description: 解決案や回避策があれば提案内容を記載してください。
      placeholder: <button />タグを<nuxt-link />に変更する。
